spring:
  security:
    oauth2:
      client:
        registration:
          battle-net:
            provider: battle-net
            client-id: ${RBGS_BNET_CLIENT_ID}
            client-secret: ${RBGS_BNET_CLIENT_SECRET}
            authorization-grant-type: authorization_code
            redirect-uri: ${RBGS_BNET_REDIRECT_URI}
            scope: openid
        provider:
          battle-net:
            issuer-uri: https://oauth.battle.net
rbgs:
  auth:
    web-origin: ${RBGS_WEB_ORIGIN}
